language: java
jdk:
  - openjdk8

branches:
  only:
    - master

cache:
  directories:
    - '$home/.m2/repository'
    - '$home/.gradle'

#트래비스 실행시 파일 실행 권한이 없음
before_install:
  - chmod +x gradlew

script: "./gradlew clean build"

before_deploy:
  - zip -r web-service *
  - mkdir -p deploy
  - mv web-service.zip deploy/web-service.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: spring-webservice-build-file
    region: ap-northeast-2
    skip_cleanup: true
    acl: private
    local_dir: deploy
    wait-until-deployed: true

notifications:
  email:
    recipients:
      - "ywan311@naver.com"